# Generated by Django 2.1 on 2021-11-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='linecons-tag', max_length=20, verbose_name='图标'),
        ),
    ]
